name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install Dependencies
              run: bun install --frozen-lockfile
            - name: Build
              run: bun --bun run build
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                  name: shaderWEB-build
                  path: build/
                  if-no-files-found: error
                  include-hidden-files: true
